name: Docker Image java api

on:
    push:
        tags:
            - '*'
    workflow_dispatch:

jobs:
    docker-build-push:
        runs-on: ubuntu-latest

        steps:
            - name: clone-codebase
              uses: actions/checkout@v2

            - name: Install Docker
              uses: docker/setup-buildx-action@v2

            - name: Build Image
                run: docker build -t java:api -f Dockerfile .
              working-directory: java